### ISSUE TITLE
4.0.12 didnt work on Kodi 17.3 RPi (noobs) installation

### ISSUE THREAD

**Issue by Delikt** [tvaddonsco/script.module.urlresolver#1]
i try a manual update of the url resolver from the git repository here... but with some addons i get a Error:

"ValueError: No JSON object could be decoded File "/usr/python2.7/json/decoder.py, line 384, in raw_decode" (need to say line 384 from 385 lines in this file)

Im running Kodi 17.3 on an 
Raspberry Pi 3 Model B (preinstalled "noobs" System i just upgraded it and install Kodi trough the Terminal)
I got also Every time a "Error cant update UrlResolver" (i also installed the looking glass repo and tried there version, it takes no effect at all) Message after i open a specific addon. This Addon install urlresolver with his own installation and have a configuration menu included) 

At all after i installed this addon all work fine for 2 days, after that i got this problem.

Any ideas?

**Comment by tvaddonsco** [comment]
Please ask at our Forums, be sure to include a full log: https://www.tvaddons.co/forums
