### ISSUE TITLE
AllDebrid API needs to be upgraded

### ISSUE THREAD

**Issue by CompKingCanada** [tvaddonsco/script.module.urlresolver#2]
In the last few days AllDebrid is no longer functioning.  AllDebrid support tells us that their old API was deactivated. 

See this thread:  https://www.tvaddons.co/forums/urlresolver-for-kodi-addons/60798-url-resolver-alldebrid.html#post424373

**Comment by tvaddonsco** [comment]
We're looking into the issue, thank you!

**Comment by tvaddonsco** [comment]
It's going to be pushed shortly!

**Comment by CompKingCanada** [comment]
Already working.  Thanks!


Geoff (from iPhone X)

**Comment by CompKingCanada** [comment]
It appears there is still an issue.  Further testing may be required

Prior to the API upgrade 90% of provided links were working.  Now less than 10% are working.

For the 2 days prior to the official release of the new URL Resolver AllDebrid was working reliably (may have been a pre-release).  This was between Dec 4-5th prior to the final release and after AllDebrided shut down the V1 API (unless they re-opened it??)

You will note this by my "Already Working - Thanks" message prior to the final release.

Please re-open ticket.
