### ISSUE TITLE
Rapidvideo.com doesnt chose highest quality

### ISSUE THREAD

**Issue by Philps** [tvaddonsco/script.module.urlresolver#28]
rapidvideo links are being resolved and played back with lowes quality 360p even though there is a higher quality available.

**Comment by Philps** [comment]
if you return get_url + the quality parameter

--> https://{host}/embed/{media_id}&q=<quality>

 it will resolve to the quality ( 360p,480p,720p,1080p )

Anyone know, where the actual resolving takes place?

**Comment by azzy9** [comment]
the "q" parameter needs to be added to the actual video before the video scraping. If the "q" query parameter provided to them doesn't exist it shows all the video links for each quality which we can use to our advantage. if it does exist it will only show that lin,. and if none is provided it will show the lowest quality

the actual resolving takes place in the generic resolver class.

if you could give #29 a go for me that would be great. :)

Also with this PR, if you disable "Automatically pick best quality" option from the main URL resolver settings it will allow you to pick the resolution when selecting the video.

**Comment by Philps** [comment]
great work. tested & working.

**Comment by azzy9** [comment]
awesome, thank you for testing 👍

**Comment by tvaddonsco** [comment]
Thank you @azzy9 for fixing this! We truly appreciate your contributions.

**Comment by azzy9** [comment]
@tvaddonsco your welcome, glad I could be of some help :)
