### ISSUE TITLE
getvi.tv  needs getmedia_url fixing

### ISSUE THREAD

**Issue by Philps** [tvaddonsco/script.module.urlresolver#30]
So far i only got the get_url part straight

class getviResolver(GenericResolver):
    print "print UR Getvi"
    name = 'getvi'
    domains = ['getvi.tv']
    pattern = None
 def get_url(self, host, media_id):        
        print "print UR Getvi return url", self._default_get_url(host, media_id, template='https://www.{host}/embed/{media_id}/')
        return self._default_get_url(host, media_id, template = 'https://www.{host}/embed/{media_id}/')

but this hit a issue that nolinks being found. 

ERROR: URLResolver: ResolverError Error - From: getvi Link: https://www.getvi.tv/embed/39446/: No Video Link Found
DEBUG: URLResolver: Traceback (most recent call last):
                                              File "script.module.urlresolver\lib\urlresolver\hmf.py", line 180, in resolve
                                                stream_url = resolver.get_media_url(self._host, self._media_id)
                                              File "script.module.urlresolver\lib\urlresolver\plugins\__generic_resolver__.py", line 49, in get_media_url
                                                return helpers.get_media_url(self.get_url(host, media_id)).replace(' ', '%20')
                                              File "script.module.urlresolver\lib\urlresolver\plugins\lib\helpers.py", line 190, in get_media_url
                                                source = pick_source(source_list)
                                              File "script.module.urlresolver\lib\urlresolver\plugins\lib\helpers.py", line 71, in pick_source
                                                raise ResolverError(common.i18n('no_video_link'))
                                            ResolverError: No Video Link Found

**Comment by azzy9** [comment]
For me the domain (http://www.getvi.tv) was down.
The https does not connect to anything.
connecting to it via http instead just connects to an empty server at the time of writing. ( it had a test php script that ran the phpinfo() function ).

I would say wait until it is all sorted before continuing.

**Comment by Philps** [comment]
when i worked on the scraper the site was up unfortunately its still/gain down
thx anyway for looking into this. hope the service is back soon

**Comment by azzy9** [comment]
Hi @Philps ,
No links are being found due to the REGEX patterns in the generic resolver matching the URL's needed for the video. Due to this we will need to create our own.

I'm thinking something like this:

`from lib import helpers
from __generic_resolver__ import GenericResolver

class getviResolver(GenericResolver):
    name = "getvi"
    domains = ["getvi.tv"]
    pattern = '(?://|\.)(getvi\.tv)/embed/([0-9A-Za-z]+)'

    def get_media_url(self, host, media_id):
        return helpers.get_media_url(self.get_url(host, media_id),patterns=['''\[(?P<label>[0-9p]+)\](?P<url>https://www.getvi.tv/(?:[^'",]+).mp4/)'''], generic_patterns=False).replace(' ', '%20')

    def get_url(self, host, media_id):
        return self._default_get_url(host, media_id, template='https://www.{host}/embed/{media_id}/')`

**Comment by Philps** [comment]
you're a star. tested & working

**Comment by azzy9** [comment]
Solved in #32

**Comment by tvaddonsco** [comment]
Thanks again @azzy9 - @Philps is definitely correct on you being a star!
