### ISSUE TITLE
Add play mode to urlresolver

### ISSUE THREAD

**Issue by koukch** [tvaddonsco/script.module.urlresolver#38]
Hello,

It would be great to add play mode to the plugin so it can be called by other plugins to play o link like:

'{"jsonrpc":"2.0","id":"1","method":"Player.Open","params":{"item":{"file":"plugin://script.module.urlresolver/?mode=play_video&uri=http://video_url"}}}'

**Comment by Eldorados** [comment]
Sorry it's not the goal of urlresolver, but would be easy to make a small addon that does the simple calls
