### ISSUE TITLE
vidzella.me broken

### ISSUE THREAD

**Issue by Philps** [tvaddonsco/script.module.urlresolver#6]
vidzella changed layout. not working anylonger

**Comment by Gujal00** [comment]
Can you post a sample embed link to troubleshoot and fix

**Comment by azzy9** [comment]
I did try to work on this but got a bit stuck.

A URL for a video on the video hosts page: https://vidzella.me/e/I9NJI58G
My attempt: https://raw.githubusercontent.com/azzy9/script.module.urlresolver/vidzella/lib/urlresolver/plugins/vidzella.py

The video host generates a unique URL on the video page in a source tag. (Example:  <source src="https://vidzella.me/stream/9PVB" type='video/mp4' />)  my attempt does retrieve this but the unique URL is suppose to provide a 302 header to the video file but my attempt in the logs show that it does not redirect and just gives a 404. Either it is missing some headers that are required for the redirect or Kodi does not handle it correctly.

**Comment by azzy9** [comment]
Hopefully #17 fixes it. It seems to work but the video host is so slow at loading that it seemed to almost crash my kodi :( but the video eventually played.
Hopefully somebody could do a more elegant fix than mine.

**Comment by Gujal00** [comment]
I think you need to append the Referer Header with the embed url for it to work correctly

**Comment by azzy9** [comment]
@Gujal00 
Hi, I am using helpers.get_media_url() which appends all the headers for me after the http get, but using it cannot see way to add my own headers before the request.
My #17 pull request works but I was hoping to pass the URL from the helpers.get_media_url() method directly to Kodi and let Kodi handle it. but instead I had to do an extra request to get the URL after the 302. Once we have the URL after the 302 we can do what we want with it before it expires as it is not restricted.

**Comment by Philps** [comment]
Fix Vidzella #17
