### ISSUE TITLE
Tune.pk - All quality options play back at 720p

### ISSUE THREAD

**Issue by rizjuan1** [tvaddonsco/script.module.urlresolver#60]
I have UrlResolver set to prompt me for the quality options before video playback. Videos from Tune.pk present the following options: 720p, 360p, 240p, and Auto. However no matter which one is selected, the video is played at 720p quality. A very minor issue but I thought I'd let you guys know.

**Comment by azzy9** [comment]
hmm.. this is due to the options basically being useless, they all return the same link in the JSON (index.m3u8). what determines the quality is the links in the index.m3u8 but I am not sure how Kodi handles this due to being a HLS. If it selects the best link for the bandwidth or not.
