### ISSUE TITLE
TheVideo.me pairing not working

### ISSUE THREAD

**Issue by dokoab** [tvaddonsco/script.module.urlresolver#69]
Pairing with thevideo.me used to work fine for months. In the pairing page it just showed my ipv4 address and it worked fine.

Now, occasionally, on the pairing page it will show both an ipv6 and ipv4 addresses, and even though I go through the pairing process, back in Kodi the countdown dialog stays there as if I didn't pair.

This only happens when thevideo.me/pair or tvad.me/pair show both my ipv6 and ipv4 addresses on the page. Openload pairing also sometimes shows these two addresses, but at least it always works.

**Comment by tvaddonsco** [comment]
We're looking into it...

**Comment by broknsymetry** [comment]
I've had this issue for many, many months.  I turn off ipv6 on my router (most applications don't require it anyway) and TheVideo/TVAD pairing (and Openload) work fine.  I realize this is just a workaround, but may give some insight into the issue and at least a temporary fix for dokoab.

**Comment by dokoab** [comment]
My router model is one generation before the one where they added the IPV6 setting, so I won't be able to try that (I'm sure it'd be the easiest solution though).
Since Openload works ok no matter what ip my ISP is giving me, this is a problem with thevideo.me and their faulty pairing process.

I wanted to know if there was a way to  circumvent that through URLResolver. I wonder if we'd get a different result if we tried sending an IPV6 request to the pairing, when the IPV4 request fails.

**Comment by dokoab** [comment]
ResolveURL supposedly fixed it (haven't tested it yet), the url for pairing is different now:
https://github.com/jsergio123/zips/tree/master/script.module.resolveurl
