### ISSUE TITLE
Please add this host, https://gofile.io. 

### ISSUE THREAD

**Issue by luhanmcs** [tvaddonsco/script.module.urlresolver#86]
Thanks and advance.

**Comment by azzy9** [comment]
Hi @luhanmcs,
It would be great if you could test #88 for me :)

**Comment by luhanmcs** [comment]
works fine, thanks. ( I tested with LSP).

**Comment by azzy9** [comment]
Awesome, thanks for testing it & letting me know :)

**Comment by tvaddonsco** [comment]
Thank you @luhanmcs for the suggestion adn @azzy9 for making it happen! <3
